### ISSUE TITLE
Can't get it to work… Any help would be appreciated!

### ISSUE THREAD

**Issue by tiagospezia** [SeptemberHX/joplin-plugin-readcube-papers#1]
Hello @SeptemberHX!!

Sorry if this is not the appropriate venue for such a message — I searched all over and as far as I can tell, this is the best place I found so far.
I tried to make the plugin work for me but Joplin doesn't seem to be changed in any way after I fill the ReadCube cookie info in the preferences. I'm not sure if I'm doing it right. Also, my subscription is in the Standard tier, not the Enterprise one. I'm guessing I may need to have an enterprise level subscription to enjoy these API features… From the ReadCube website, I'm not sure if the API feature as it relates to Standard/Enterprise subscriptions is related to plugin developmen t capabilities or to anything related to plugins…
Any help you can offer will be greatly appreciated.
Thanks!

**Comment by SeptemberHX** [comment]
Only standard subscription is tested for now because my subscription is standard :)

After installing the plugin and setting the cookie, you can see two new buttons. Try to click the left button to check whether it works or not.

<img width="755" alt="image" src="https://user-images.githubusercontent.com/18042424/181664528-44fe6eb7-a4aa-42e6-8468-f6689463d433.png">

If everything works, a selection dialog will popup:

<img width="957" alt="image" src="https://user-images.githubusercontent.com/18042424/181664650-f73f4362-c8bd-491e-9871-d1b5152ff453.png">

If you want to create a note for a paper, go to: "Tools -> Enhancement -> Create note for paper"

**Comment by tiagospezia** [comment]
Hello again! Sorry it took me this long to reply…
I must be doing something wrong with the cookies, as I don't even get to the point of getting the interface to show the buttons. I tried copying the cookie value for all of the cookies individually, but I can't get it to work. I assume these are the cookies in question... The Value strings are not complete in the screenshot, but I guess that's what we're talking about, right?

![CleanShot 2022-08-15 at 14 03 22](https://user-images.githubusercontent.com/64706514/184682291-d73d7c6c-58e7-436a-8736-0fe300ec4e73.png)

**Comment by SeptemberHX** [comment]
The copied cookie should look like:

```cookie
_readcube_session=XXXXXXX; user_web_token=XXXXXXX; _redcube-login_token=XXXXXXX
```

Please follow the instruction in `Readme.md` to get the cookie.

You can also toggle the dev tools in Joplin to check whether there exist some errors: Joplin -> help -> open/close the dev tools. Then switch to the `console` tab, and check whether there are messages in red color.

**Comment by tiagospezia** [comment]
Thank you so much!
Following the syntax from the above comment, I got it to work. I had already tried everything, but I didn't see this syntax mentioned in the `Readme.md`. Now I'll try to put it to some real use!
Again, thanks @SeptemberHX !!!

**Comment by SeptemberHX** [comment]
I will update the `Readme.md` with more information of the cookie. Thanks for your feedback.
